-- AFROBACK Mobile — schéma Postgres pour le pilier Découverte
-- Généré le 2026-07-31 à partir de
-- livrables/sites-web/afroback/app-mobile/data-model-decouverte.md

create extension if not exists pgcrypto;

create table if not exists public.decouverte_items (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  type text not null check (type in ('village', 'coutume', 'objet', 'personnage', 'fait')),
  pays text not null,
  region_ethnie text not null,
  titre text not null,
  sous_titre text not null,
  resume_liste text not null,
  contenu_fr_texte text not null,
  contenu_en_texte text,
  statut_fait_legende jsonb not null default '[]',
  image_url text,
  sources text[] not null default '{}',
  heros_lies text[] not null default '{}',
  items_lies text[] not null default '{}',
  statut_contenu text not null default 'pret',
  ordre_affichage integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.decouverte_pays (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  nom text not null,
  resume text not null,
  ordre_affichage integer not null default 0
);

alter table public.decouverte_items enable row level security;
alter table public.decouverte_pays enable row level security;

drop policy if exists "Public read access" on public.decouverte_items;
create policy "Public read access" on public.decouverte_items
  for select
  using (true);

drop policy if exists "Public read access" on public.decouverte_pays;
create policy "Public read access" on public.decouverte_pays
  for select
  using (true);

-- Écriture réservée au rôle service_role (dashboard / futur back-office),
-- jamais au rôle anon utilisé par l'app mobile.

truncate table public.decouverte_items;
truncate table public.decouverte_pays;

insert into public.decouverte_pays (slug, nom, resume, ordre_affichage) values (
  'cameroun',
  'Cameroun',
  'Premier pays couvert par le pilier Découverte d''AFROBACK : villages, traditions, objets et rôles traditionnels des royaumes et peuples déjà croisés dans le pilier Histoires & Héros (Bamoun, Sawa, Bulu/Beti).',
  0
);

insert into public.decouverte_items (slug, type, pays, region_ethnie, titre, sous_titre, resume_liste, contenu_fr_texte, contenu_en_texte, statut_fait_legende, image_url, sources, heros_lies, items_lies, statut_contenu, ordre_affichage) values (
  'fon-chef-traditionnel-bamoun',
  'personnage',
  'Cameroun',
  'Royaume Bamoun, Ouest Cameroun',
  'Le fon, chef traditionnel bamoun',
  'Gardien de l''ordre social, lien vivant entre les ancêtres et le peuple',
  'Dans le royaume bamoun, le souverain traditionnel, ou Mfon, cumule des fonctions militaires, judiciaires et diplomatiques héritées de siècles de tradition. Sa position, héréditaire, est aussi rituelle : le Nguon rappelle régulièrement que son pouvoir n''est jamais absolu, mais redevable devant son peuple.',
  'Dans les Grassfields de l''Ouest camerounais, la figure du chef traditionnel occupe une place que peu d''institutions occidentales permettent de comprendre d''emblée. Chez les Bamoun, ce chef porte le titre de Mfon (le mot "fon" désignant plus largement le souverain dans les chefferies voisines des Grassfields, et le titre de "sultan" étant aussi couramment employé depuis l''islamisation de la cour bamoun). Sa fonction est héréditaire, transmise au sein des lignées patrilinéaires du royaume, et ses attributions dépassent largement le protocolaire : traditionnellement, il commande l''armée, contrôle la justice coutumière, et négocie les alliances et les tensions avec les chefferies et royaumes voisins.

Ce pouvoir n''est cependant pas conçu, dans la culture bamoun, comme purement politique. Selon la conception traditionnelle, le chef est investi d''un prestige de nature sacrée : il incarne la puissance des ancêtres fondateurs du royaume et sert de trait d''union entre le monde des vivants et celui des ancêtres, ce qui fait de lui, autant qu''un chef d''État, un gardien du lien spirituel qui tient la communauté ensemble. C''est précisément ce double statut, politique et sacré, qui rend le Nguon si significatif : cette grande assemblée bisannuelle où le peuple bamoun questionne publiquement la gouvernance de son chef, et peut le sanctionner en cas de manquement, rappelle que même un pouvoir de nature sacrée reste, chez les Bamoun, un pouvoir redevable. La tradition rapporte également que le chef est entouré d''un collège de notables consultés sur les grandes étapes du règne, une pratique bien documentée chez les chefferies bamiléké voisines des Grassfields, mais dont l''application précise à la cour bamoun reste moins solidement établie dans les sources consultées.

L''institution a traversé la colonisation et continue d''exister aujourd''hui dans le cadre juridique camerounais : depuis un décret de 1977, les chefferies traditionnelles, dont celle des Bamoun, sont des institutions reconnues par l''État, hiérarchisées en trois degrés selon leur importance historique et territoriale. Le chef y conserve un statut d''auxiliaire de l''administration et un rôle d''arbitrage dans les litiges coutumiers, familiaux, successoraux ou fonciers, dans les limites fixées par la loi. Le chef traditionnel bamoun d''aujourd''hui navigue ainsi entre deux mondes : héritier d''une légitimité ancestrale et rituelle profondément enracinée, et acteur reconnu, quoique encadré, de l''administration camerounaise contemporaine.',
  null,
  '[{"affirmation":"Dans le royaume bamoun, le souverain porte le titre de Mfon, aussi rendu par \"sultan\" depuis l''islamisation de la cour","statut":"atteste"},{"affirmation":"La fonction de chef est héréditaire, transmise au sein de lignées patrilinéaires","statut":"atteste"},{"affirmation":"Le chef commande traditionnellement l''armée, contrôle la justice coutumière et négocie avec les chefferies voisines","statut":"atteste"},{"affirmation":"Selon la conception traditionnelle bamoun, le chef est investi d''un prestige sacré et incarne le lien entre les vivants et les ancêtres","statut":"tradition_orale"},{"affirmation":"Le Nguon illustre concrètement la redevabilité du chef : il y est publiquement questionné sur sa gouvernance et peut être sanctionné","statut":"atteste"},{"affirmation":"Le chef est traditionnellement entouré d''un collège de notables consultés lors des grandes étapes du règne","statut":"tradition_orale"},{"affirmation":"Depuis le décret n°77/245 de 1977, les chefferies traditionnelles camerounaises, dont la chefferie bamoun, sont des institutions reconnues par l''État, hiérarchisées en trois degrés","statut":"atteste"},{"affirmation":"Le chef traditionnel conserve aujourd''hui un statut d''auxiliaire de l''administration et un rôle d''arbitrage dans les litiges coutumiers, dans les limites fixées par la loi","statut":"atteste"}]'::jsonb,
  'https://ygkyapryramhaskfbrrt.supabase.co/storage/v1/object/public/heroes-media/images/decouverte/fon-chef-traditionnel-bamoun.jpg',
  ARRAY['[Bamum | History, Language & Culture — Britannica](https://www.britannica.com/topic/Bamum)', '[Chefferies traditionnelles au Cameroun — Wikipédia](https://fr.wikipedia.org/wiki/Chefferies_traditionnelles_au_Cameroun)', '[Civilisation des grassfields — Les cours du lycée](https://mes-cours.over-blog.com/2019/07/civilisation-des-grassfields.html)', '[Dans les arcanes des chefferies de l''ouest et du nord-ouest du Cameroun — Makanisi](https://www.makanisi.org/dans-les-arcanes-des-chefferies-de-louest-et-du-nord-ouest-du-cameroun/)', 'Fiche Découverte "Le Nguon" (même dossier), pour l''illustration du principe de redevabilité du chef']::text[],
  ARRAY['sultan-njoya']::text[],
  ARRAY['palais-royal-foumban', 'nguon', 'trone-mandu-yenu']::text[],
  'pret',
  0
);

insert into public.decouverte_items (slug, type, pays, region_ethnie, titre, sous_titre, resume_liste, contenu_fr_texte, contenu_en_texte, statut_fait_legende, image_url, sources, heros_lies, items_lies, statut_contenu, ordre_affichage) values (
  'nguon',
  'coutume',
  'Cameroun',
  'Royaume Bamoun, Ouest Cameroun',
  'Le Nguon',
  'La grande assemblée bamoun où le peuple juge la gouvernance de son roi',
  'Tous les deux ans, le royaume bamoun se rassemble autour du Nguon, une série de rituels vieille de plusieurs siècles où le souverain répond publiquement de sa gouvernance devant son peuple. Reconnu par l''UNESCO comme patrimoine culturel immatériel de l''humanité en 2023, le Nguon mêle jugement populaire, réconciliation et grande fête collective.',
  'Le Nguon est l''un des rituels de gouvernance les plus singuliers d''Afrique centrale : pendant trois jours, tous les deux ans (les années paires, en général début décembre), le royaume bamoun se réunit autour d''une question simple et exigeante, celle de la manière dont le roi, le Mfon, a exercé son pouvoir depuis la dernière édition. La tradition orale bamoun rattache l''origine de cette pratique à la fondation même du royaume, à la fin du XIVe siècle, et lui prête à l''origine un lien avec les récoltes et avec le scarabée, un insecte dont le vol en essaim aurait inspiré aux ancêtres bamoun une image de la cohésion collective, celle-là même que le rituel cherche à entretenir.

Le déroulement du Nguon suit trois grandes phases. D''abord le Shâpam, une phase de préparation rituelle où le roi reçoit des chefs coutumiers des éléments censés renouveler sa force et sa sagesse. Vient ensuite le moment le plus spectaculaire, le Kûmutngu : les chefs rituels, après avoir recueilli en amont et dans la discrétion les doléances de la population, exposent publiquement au roi les manquements de son règne, une forme de procès populaire au terme duquel il peut être sanctionné, voire, dans les cas les plus graves selon la tradition, destitué. S''il obtient un mandat renouvelé, le roi prononce un discours d''acceptation et le pardon est scellé. La troisième phase, le Shômelue, prend la forme d''une reconstitution guerrière rejouant des épisodes du passé du royaume, suivie d''un défilé triomphal qui referme la cérémonie dans la liesse collective.

Cette tradition n''a pas traversé le XXe siècle sans rupture. Les autorités coloniales françaises, jugeant sans doute la mise en cause publique du souverain incompatible avec l''ordre colonial, interdisent sa célébration à partir de 1924, alors que règne le roi Ibrahim Njoya. Le Nguon renaît que très progressivement dans les décennies suivantes, avec des célébrations ponctuelles, avant d''être pleinement restauré comme grand rendez-vous régulier du royaume au début des années 1990, sous le règne du roi Ibrahim Mbombo Njoya, et célébré depuis de façon biennale. En décembre 2023, l''UNESCO a inscrit le Nguon sur sa Liste représentative du patrimoine culturel immatériel de l''humanité, reconnaissant à la fois sa valeur culturelle et sa portée universelle : un mécanisme rituel de dialogue, de redevabilité et de réconciliation entre un souverain et son peuple.',
  null,
  '[{"affirmation":"Le Nguon est une pratique rituelle vieille de plus de six siècles chez les Bamoun","statut":"atteste"},{"affirmation":"La tradition orale rattache l''origine du Nguon à la fondation du royaume par Nchare Yen, à la fin du XIVe siècle","statut":"tradition_orale"},{"affirmation":"Le nom \"Nguon\" désignerait à l''origine un scarabée dont le vol aurait inspiré des valeurs de cohésion aux ancêtres bamoun","statut":"tradition_orale"},{"affirmation":"Le Nguon se tient tous les deux ans (années paires), en général début décembre, sur une période de trois jours","statut":"atteste"},{"affirmation":"Le rituel se déroule en trois grandes phases : Shâpam (préparation rituelle du roi), Kûmutngu (jugement public de sa gouvernance), Shômelue (reconstitution guerrière et défilé triomphal)","statut":"atteste"},{"affirmation":"Le roi jugé peut être sanctionné, voire destitué en cas de manquement grave selon la tradition","statut":"atteste"},{"affirmation":"Le Nguon a été interdit par l''administration coloniale française à partir de 1924, sous le règne du roi Ibrahim Njoya","statut":"atteste"},{"affirmation":"Le Nguon a été progressivement réhabilité à partir de la fin des années 1950, puis restauré comme grand rendez-vous biennal régulier au début des années 1990","statut":"atteste"},{"affirmation":"Le Nguon a été inscrit sur la Liste représentative du patrimoine culturel immatériel de l''humanité de l''UNESCO en décembre 2023","statut":"atteste"}]'::jsonb,
  'https://ygkyapryramhaskfbrrt.supabase.co/storage/v1/object/public/heroes-media/images/decouverte/nguon.jpg',
  ARRAY['[Nguon, rituals of governance and associated expressions in the Bamoun community — UNESCO Intangible Cultural Heritage](https://ich.unesco.org/en/RL/nguon-rituals-of-governance-and-associated-expressions-in-the-bamoun-community-01955)', '[Ngouon — Wikipédia](https://fr.wikipedia.org/wiki/Ngouon)', '[Le festival Nguon, aussi populaire qu''incontournable ! — Badalfohmoh](https://badalfohmoh.mondoblog.org/parlons-du-festival-nguon/)', '[Historique – Rituels de gouvernance et expressions associées dans la communauté Bamoun](https://nguonevent.com/historique/)']::text[],
  ARRAY['sultan-njoya']::text[],
  ARRAY['palais-royal-foumban', 'trone-mandu-yenu', 'fon-chef-traditionnel-bamoun']::text[],
  'pret',
  1
);

insert into public.decouverte_items (slug, type, pays, region_ethnie, titre, sous_titre, resume_liste, contenu_fr_texte, contenu_en_texte, statut_fait_legende, image_url, sources, heros_lies, items_lies, statut_contenu, ordre_affichage) values (
  'palais-royal-foumban',
  'village',
  'Cameroun',
  'Royaume Bamoun, Ouest Cameroun',
  'Palais royal de Foumban',
  'Résidence des rois bamoun, mémoire vivante d''un royaume six fois centenaire',
  'Au cœur de Foumban, capitale historique du royaume bamoun, le palais royal abrite depuis des générations la résidence du souverain. Reconstruit au début du XXe siècle après plusieurs incendies, il mêle influences architecturales locales et européennes, et loge aujourd''hui un musée qui retrace six siècles de dynastie.',
  'Foumban est la capitale du royaume bamoun depuis sa fondation, à la fin du XIVe siècle, par le prince Nchare Yen, venu de la dynastie Tikar. Pendant des générations, les souverains successifs y ont fait bâtir leur résidence, reconstruite à plusieurs reprises au fil des règnes et des aléas de l''histoire : les palais antérieurs, faits de bambou et de chaume, ont été détruits par des incendies avant que le roi Ibrahim Njoya, le plus connu des souverains bamoun, ne fasse édifier au tout début du XXe siècle la structure de pierre et de brique qui se dresse encore aujourd''hui à Foumban. Le résultat est une architecture singulière en Afrique centrale, à mi-chemin entre la résidence princière et une allure de forteresse, que la tradition populaire locale rattache à l''admiration de Njoya pour la résidence du gouverneur allemand qu''il avait visitée à Buea.

Le palais n''est pas un monument figé : il est resté, jusqu''à aujourd''hui, la résidence effective du souverain bamoun, tout en abritant en son sein un musée qui présente au public une partie du patrimoine royal, des coiffes et parures aux instruments de musique, en passant par les manuscrits liés à l''écriture bamoun. Dans les années 1990, un programme de rénovation soutenu par l''UNESCO a permis de restaurer l''édifice, qui menaçait de se dégrader, et de lui rendre une partie de son éclat d''origine.

Plus récemment, en avril 2024, un nouveau Musée royal bamoun de grande ampleur (environ 5 000 m²) a été inauguré à quelques pas du palais historique. Il rassemble aujourd''hui l''essentiel des collections royales, plusieurs milliers d''objets accumulés sur six siècles de règnes successifs, offrant un écrin plus vaste et mieux équipé pour préserver ce patrimoine, tandis que le palais continue de vivre comme lieu de résidence et de cérémonies. Cette dispersion progressive des collections royales dans les musées, camerounais mais aussi européens, ravive régulièrement le débat sur la restitution des objets emportés pendant la période coloniale, un sujet encore ouvert et discuté aussi bien par les historiens que par les autorités bamoun elles-mêmes.',
  null,
  '[{"affirmation":"Le royaume bamoun a été fondé à la fin du XIVe siècle par le prince Nchare Yen, issu de la dynastie Tikar","statut":"atteste"},{"affirmation":"Foumban est la capitale historique du royaume depuis sa fondation","statut":"atteste"},{"affirmation":"Le palais actuel a été reconstruit au tout début du XXe siècle sous le règne du roi Ibrahim Njoya, après la destruction par le feu des palais antérieurs en bambou et chaume","statut":"atteste"},{"affirmation":"La date précise d''achèvement du palais actuel varie selon les sources (autour de 1917-1921)","statut":"debattu"},{"affirmation":"Njoya se serait inspiré de la résidence du gouverneur allemand de Buea pour dessiner les plans du palais","statut":"tradition_orale"},{"affirmation":"Le palais a fait l''objet d''un programme de rénovation soutenu par l''UNESCO dans les années 1990","statut":"atteste"},{"affirmation":"Un nouveau Musée royal bamoun, voisin du palais, a été inauguré le 13 avril 2024 et rassemble plusieurs milliers d''objets couvrant six siècles d''histoire","statut":"atteste"},{"affirmation":"Le palais continue aujourd''hui d''abriter la résidence du souverain bamoun en exercice","statut":"atteste"},{"affirmation":"La restitution d''objets du patrimoine bamoun emportés pendant la période coloniale reste un sujet de débat actuel","statut":"debattu"}]'::jsonb,
  'https://ygkyapryramhaskfbrrt.supabase.co/storage/v1/object/public/heroes-media/images/decouverte/palais-royal-foumban.jpg',
  ARRAY['[Foumban | Traditional Crafts, Royal Palace & Music | Britannica](https://www.britannica.com/place/Foumban)', '[Foumban Royal Palace — Wikipedia](https://en.wikipedia.org/wiki/Foumban_Royal_Palace)', '[Kingdom of Bamum — Wikipedia](https://en.wikipedia.org/wiki/Kingdom_of_Bamum)', '[Au palais des sultans à Foumban : République unie du Cameroun (mission) — UNESCO](https://unesdoc.unesco.org/ark:/48223/pf0000065344)', '[Musée des rois Bamoun : des trésors anciens du Cameroun trouvent un nouvel écrin spectaculaire — The Conversation](https://theconversation.com/musee-des-rois-bamoun-des-tresors-anciens-du-cameroun-trouvent-un-nouvel-ecrin-spectaculaire-244911)', '[Le Palais des Sultans Bamoun : Un trésor historique au cœur de Foumban — SweetTravelTime](https://sweettraveltime.com/le-palais-des-sultans-bamoun-un-tresor-historique-au-coeur-de-foumban/)']::text[],
  ARRAY['sultan-njoya']::text[],
  ARRAY['nguon', 'trone-mandu-yenu', 'fon-chef-traditionnel-bamoun']::text[],
  'pret',
  2
);

insert into public.decouverte_items (slug, type, pays, region_ethnie, titre, sous_titre, resume_liste, contenu_fr_texte, contenu_en_texte, statut_fait_legende, image_url, sources, heros_lies, items_lies, statut_contenu, ordre_affichage) values (
  'trone-mandu-yenu',
  'objet',
  'Cameroun',
  'Royaume Bamoun, Ouest Cameroun',
  'Le trône Mandu Yenu',
  'Le trône royal perlé bamoun, chef-d''œuvre d''art et objet de mémoire coloniale',
  'Le Mandu Yenu, "riche en perles", est l''un des trônes les plus célèbres d''Afrique centrale : un siège et un repose-pieds en bois entièrement recouverts de perles de verre et de cauris, sculptés des symboles du pouvoir bamoun. Offert en 1908 à l''empereur allemand Guillaume II, il est aujourd''hui conservé à Berlin, et son histoire continue d''interroger la mémoire coloniale du royaume.',
  'Dans l''art royal bamoun, aucun objet ne condense mieux le prestige du souverain que son trône. Le Mandu Yenu, dont le nom signifie "riche en perles" en langue bamoun, en est l''exemple le plus abouti : une pièce en deux parties, un siège et un repose-pieds, sculptées dans du bois massif puis intégralement recouvertes d''un habillage de perles de verre importées d''Europe et de cauris venus de l''océan Indien, cousus un à un sur l''armature de bois selon des motifs précis. Les sculptures qui structurent l''ensemble ne sont pas décoratives au sens où on l''entendrait en Occident : elles portent les symboles du pouvoir bamoun, à commencer par le serpent à deux têtes et l''araignée de la terre, figure associée à la sagesse et à la divination, ainsi que des figures humaines qui représentent la protection royale et la force militaire du royaume. Porter ce trône dans les cérémonies, c''était donc littéralement s''asseoir sur les symboles de la légitimité du pouvoir.

L''histoire de ce trône particulier a basculé en 1908, lorsque le roi Ibrahim Njoya en fit don à l''empereur allemand Guillaume II, alors que le royaume bamoun était sous administration coloniale allemande. Les récits sur les circonstances exactes de ce don divergent : certaines sources le rattachent à une expédition militaire menée conjointement par les troupes coloniales allemandes et celles du royaume bamoun contre le royaume voisin du Nso'', d''autres évoquent une démarche des autorités allemandes qui souhaitaient initialement une réplique du trône pour l''anniversaire de l''empereur avant d''obtenir l''objet original. Ce qui est certain, c''est que Njoya conserva une réplique du trône à Foumban tandis que l''original prenait la direction de Berlin. Cette histoire soulève aujourd''hui une question à laquelle historiens et institutions muséales n''apportent pas de réponse unique : un don consenti dans le contexte de rapports de force coloniaux profondément inégaux peut-il vraiment être qualifié de don libre ? C''est cette tension, entre chef-d''œuvre artistique et objet de mémoire coloniale, qui continue de façonner le regard porté sur le Mandu Yenu.

Aujourd''hui, l''original du trône est conservé à l''Ethnologisches Museum de Berlin, où il demeure l''une des pièces les plus documentées de l''art bamoun hors du continent africain, tandis que le palais royal de Foumban continue d''abriter sa réplique et d''autres trônes perlés, témoins vivants d''une tradition d''orfèvrerie textile et de perlage qui reste pratiquée aujourd''hui par les artisans bamoun.',
  null,
  '[{"affirmation":"Le Mandu Yenu est un trône royal bamoun composé d''un siège et d''un repose-pieds sculptés dans le bois","statut":"atteste"},{"affirmation":"Il est entièrement recouvert de perles de verre importées d''Europe et de cauris de l''océan Indien","statut":"atteste"},{"affirmation":"Les sculptures représentent des symboles royaux, notamment le serpent à deux têtes et l''araignée de la terre associée à la sagesse","statut":"atteste"},{"affirmation":"Le roi Ibrahim Njoya a offert le trône à l''empereur allemand Guillaume II en 1908","statut":"atteste"},{"affirmation":"Les circonstances précises de ce don (lien avec une expédition militaire commune contre le Nso'', ou demande initiale d''une réplique pour l''anniversaire de l''empereur) varient selon les sources","statut":"debattu"},{"affirmation":"La question de savoir si ce don peut être qualifié de pleinement volontaire, compte tenu du contexte colonial, fait débat parmi historiens et institutions muséales","statut":"debattu"},{"affirmation":"Njoya aurait fait fabriquer une réplique du trône conservée au palais de Foumban","statut":"atteste"},{"affirmation":"L''original du trône est aujourd''hui conservé à l''Ethnologisches Museum de Berlin","statut":"atteste"}]'::jsonb,
  'https://ygkyapryramhaskfbrrt.supabase.co/storage/v1/object/public/heroes-media/images/decouverte/trone-mandu-yenu.jpg',
  ARRAY['[Focus on collection holdings: "Mandu Yenu": The Royal Throne of Bamum — Ethnologisches Museum / Staatliche Museen zu Berlin](https://www.smb.museum/en/museums-institutions/ethnologisches-museum/collection-research/focus-on-collection-holdings/mandu-yenu-the-royal-throne-of-bamum/)', '[Museum of the Bamoun Kings: ancient treasures from Cameroon find a spectacular new home — The Conversation](https://theconversation.com/museum-of-the-bamoun-kings-ancient-treasures-from-cameroon-find-a-spectacular-new-home-244320)', '[Bamoun – Quintessence Africaine](https://laquintessenceafricaine.com/collections/bamoun)', '[Royal Art from the Grasslands of Cameroon — The Bamoun Collection](https://www.thebamouncollection.com/royal-art-from-the-grasslands-of-cameroon)']::text[],
  ARRAY['sultan-njoya']::text[],
  ARRAY['palais-royal-foumban', 'nguon', 'fon-chef-traditionnel-bamoun']::text[],
  'pret',
  3
);

insert into public.decouverte_items (slug, type, pays, region_ethnie, titre, sous_titre, resume_liste, contenu_fr_texte, contenu_en_texte, statut_fait_legende, image_url, sources, heros_lies, items_lies, statut_contenu, ordre_affichage) values (
  'ebolowa',
  'village',
  'Cameroun',
  'Pays Bulu/Beti, sud/centre Cameroun',
  'Ebolowa',
  'La ville née d''un siège, capitale du pays bulu forgée dans la résistance à la colonisation allemande',
  'Aujourd''hui chef-lieu de la région du Sud, Ebolowa est née à la charnière du XIXe et du XXe siècle, entre l''installation d''une mission américaine et celle d''un poste militaire allemand. La ville a été le théâtre, au tout début des années 1900, d''un des affrontements les plus marquants entre les royaumes et confédérations bulu et l''administration coloniale allemande.',
  'Le site qui deviendra Ebolowa apparaît dans les récits historiques à la fin des années 1890, quand des missionnaires presbytériens américains, dont le docteur Adolphus C. Good, s''installent dans la région en suivant l''axe Kribi-Lolodorf, avec l''aval des autorités allemandes qui y voient aussi l''occasion d''étendre leur emprise administrative sur l''arrière-pays. Autour de cette double présence, missionnaire et militaire, un poste colonial allemand se forme sur la colline connue localement sous le nom d''Ebolowa-si.

Le nom même de la ville porte une légende locale, largement répandue mais impossible à authentifier avec certitude : un chasseur du nom de Zanga Mba serait tombé sur la carcasse en décomposition d''un grand singe et se serait exclamé « Ebolowo''o », c''est-à-dire « voici le chimpanzé pourri » ; les soldats allemands présents auraient mal saisi le mot, le répétant en « Ebolowa », qui aurait fini par s''imposer comme nom du lieu.

C''est surtout la guerre de 1903, parfois prolongée jusqu''en 1904 selon les sources, qui a fait entrer Ebolowa dans l''histoire de la résistance camerounaise. Le chef bulu Evina Minko''o, du village d''Azem, dans les environs immédiats de la ville, mobilise plusieurs milliers de guerriers bulu, en confédération avec d''autres groupes de la région, pour venger des proches tués par les Allemands et pour s''opposer à leur avancée. Le récit du siège lui-même diverge fortement selon les sources : les récits de tradition orale relayés par la presse camerounaise rapportent une victoire bulu, avec un blocus d''un mois qui aurait contraint la garnison allemande à évacuer la ville vers Kribi fin février 1903 ; un ouvrage plus académique sur la résistance de l''hinterland sud décrit au contraire une confrontation prolongée sur plus d''un an, avec des pertes lourdes des deux côtés, et une issue finalement défavorable aux Bulu, scellée par une paix négociée. Ce que les deux versions confirment, en revanche, c''est l''ampleur de la mobilisation bulu (les chiffres varient de plusieurs milliers à plus de dix mille combattants selon les épisodes et les sources) et la réalité d''une résistance armée organisée, bien après que d''autres régions du pays avaient déjà été soumises.

Après cette période, l''ensemble de la région est progressivement « pacifiée » par l''administration allemande, un processus que les historiens situent globalement autour de 1907. Ebolowa devient alors un centre administratif colonial durable, puis, sous administration française, un chef-lieu régional, statut qu''elle conserve aujourd''hui comme capitale de la région du Sud du Cameroun, carrefour agricole (cacao notamment) et administratif du pays bulu.',
  null,
  '[{"affirmation":"Des missionnaires presbytériens américains, dont Adolphus C. Good, s''installent dans la région d''Ebolowa à la fin des années 1890","statut":"atteste"},{"affirmation":"Un poste colonial allemand se met en place sur la colline d''Ebolowa-si à la même période","statut":"atteste"},{"affirmation":"L''étymologie populaire du nom \"Ebolowa\" (« chimpanzé pourri » mal compris par des soldats allemands)","statut":"tradition_orale"},{"affirmation":"Le chef bulu Evina Minko''o, d''Azem, a mené une résistance armée mobilisant plusieurs milliers de guerriers bulu contre les Allemands au début des années 1900","statut":"atteste"},{"affirmation":"Le déroulement précis et l''issue du siège d''Ebolowa (victoire bulu avec repli allemand vers Kribi, contre confrontation prolongée se soldant par une paix négociée défavorable aux Bulu)","statut":"debattu"},{"affirmation":"Le nombre exact de combattants mobilisés varie fortement selon les sources (de l''ordre de 6 000 à plus de 14 000 selon les épisodes)","statut":"debattu"},{"affirmation":"La région est considérée par les historiens comme globalement « pacifiée » par l''administration allemande vers 1907","statut":"atteste"},{"affirmation":"Ebolowa est aujourd''hui le chef-lieu de la région du Sud du Cameroun","statut":"atteste"}]'::jsonb,
  'https://ygkyapryramhaskfbrrt.supabase.co/storage/v1/object/public/heroes-media/images/decouverte/ebolowa.jpg',
  ARRAY['Joseph Owona, *Kamerun : les résistants oubliés de l''hinterland Sud à la pénétration allemande (1889-1918)*, préface de Kpwang K. Robert (texte intégral consulté sur archive.org)', '[L''histoire du résistant bulu qui défia les Allemands avec 14 000 combattants — Coups Francs](https://www.coupsfrancs.com/lhistoire-du-resistant-bulu-qui-defia-les-allemands-avec-14000-combattants/)', '[Livre : Enoh Meyomesse raconte la guerre entre Bulu et les Allemands à Ebolowa en 1903 — ActuCameroun](https://actucameroun.com/2021/10/19/livre-enoh-meyomesse-raconte-la-guerre-entre-bulu-et-les-allemands-a-ebolowa-en-1903/)', '[Voici les origines des noms de 25 principales villes du Cameroun — ActuCameroun](https://actucameroun.com/2026/04/14/voici-les-origines-des-noms-de-25-principales-villes-du-cameroun/)', '[Histoire de la Ville d''Ebolowa — Osidimbea, La Mémoire du Cameroun](https://www.osidimbea.cm/collectivites/sud/ebolowa/)', '[Histoire coloniale du Cameroun — Wikipédia](https://fr.wikipedia.org/wiki/Histoire_coloniale_du_Cameroun)']::text[],
  ARRAY['martin-paul-samba', 'charles-atangana']::text[],
  ARRAY['rite-initiatique-so', 'nkukuma-notable-lignage']::text[],
  'pret',
  4
);

insert into public.decouverte_items (slug, type, pays, region_ethnie, titre, sous_titre, resume_liste, contenu_fr_texte, contenu_en_texte, statut_fait_legende, image_url, sources, heros_lies, items_lies, statut_contenu, ordre_affichage) values (
  'nkukuma-notable-lignage',
  'personnage',
  'Cameroun',
  'Pays Bulu/Beti, sud/centre Cameroun',
  'Le nkukuma, notable de lignage',
  'L''homme d''autorité dans une société sans roi, où le statut se conquiert plus qu''il ne se hérite',
  'Contrairement au royaume bamoun et à son fon, la société beti/bulu traditionnelle ne connaissait pas de chef centralisé unique avant la colonisation. L''autorité y reposait sur des notables de lignage, les nkukuma, des hommes qui construisaient leur influence par la richesse redistribuée, l''éloquence et le courage, à l''échelle d''un village ou d''un groupe de villages seulement.',
  'Décrire un « chef traditionnel beti/bulu » comme on décrirait un fon bamoun serait trompeur, et c''est précisément ce qui rend cette figure intéressante. Les ethnologues qui ont étudié en profondeur les sociétés beti, bulu et fang, au premier rang desquels Philippe Laburthe-Tolra, s''accordent à dire que ces peuples n''ont pas connu, avant la période coloniale, d''organisation politique centralisée comparable aux royaumes de l''Ouest camerounais : ni dynastie, ni capitale unique, ni souverain dont l''autorité s''étendrait au-delà d''un village ou d''un groupe de villages apparentés. Certains chercheurs qualifient cette organisation d''« acéphale », littéralement « sans tête » ; d''autres nuancent ce terme, jugé un peu réducteur, en rappelant que l''absence de pouvoir politique centralisé n''empêchait pas l''existence de statuts sociaux différenciés et d''une hiérarchie bien réelle à l''échelle locale. Le débat sur le terme exact reste ouvert chez les spécialistes ; ce qui fait consensus, en revanche, c''est l''absence d''un pouvoir centralisé de type royal.

Dans ce cadre, la figure qui se rapproche le plus d''un « homme d''autorité » est le nkukuma, littéralement l''« homme véritablement riche ». Mais la richesse seule n''y suffit pas : la tradition orale et les travaux d''ethnologues rapportent qu''un notable digne de ce nom devait réunir plusieurs qualités à la fois, la vaillance et le courage (ayog), le don de la parole et la maîtrise des proverbes pour arbitrer les conflits avec justesse, et surtout la générosité (akàb), considérée comme la vertu cardinale : la richesse d''un nkukuma n''avait de sens que si elle était partagée et redistribuée, d''abord à ses descendants et à ses proches, puis plus largement à ceux qui se plaçaient sous sa protection. L''ancienneté (le principe du ntol, la préséance liée à l''âge) comptait aussi, mais restait secondaire face à la compétence réelle : un homme plus jeune mais plus capable pouvait dépasser en influence un aîné moins doué. Un nkukuma particulièrement reconnu pouvait accéder au titre de njoé bôt, une forme de chef, mais dont l''autorité restait limitée à son village ou à son groupe de villages, sans pouvoir contraignant sur des sujets au sens où l''entendrait une monarchie centralisée. C''est notamment au sein des sociétés d''initiation comme le Sô que ces hommes affirmés trouvaient un lieu d''exercice de leur influence, en intégrant le cercle des initiés consultés sur les affaires de la communauté.

Il faut noter, enfin, que la figure du « chef » plus formalisée que l''histoire coloniale associe souvent aux Beti et aux Bulu (chef de canton, chef supérieur) est en bonne partie une création administrative allemande puis française, qui a désigné ou officialisé certains notables locaux pour servir de relais à l''autorité coloniale, un usage bien documenté par les historiens du Cameroun colonial mais qui ne doit pas être confondu avec l''organisation politique précoloniale elle-même.',
  null,
  '[{"affirmation":"Les sociétés beti/bulu précoloniales n''avaient pas d''organisation politique centralisée comparable à une monarchie (pas de dynastie unique, pas de capitale royale)","statut":"atteste"},{"affirmation":"Le terme « société acéphale » pour qualifier cette organisation fait débat entre spécialistes : certains le jugent réducteur car il n''exclut pas l''existence de hiérarchies sociales locales","statut":"debattu"},{"affirmation":"Le nkukuma désigne un notable dont l''autorité repose sur la richesse redistribuée, l''éloquence, le courage et la générosité, plus que sur l''hérédité seule","statut":"atteste"},{"affirmation":"Un nkukuma reconnu pouvait accéder au titre de njoé bôt, une forme de chef à l''autorité limitée à un village ou un groupe de villages","statut":"atteste"},{"affirmation":"Le principe de préséance par l''âge (ntol) existait mais pouvait être dépassé par la compétence individuelle","statut":"atteste"},{"affirmation":"Les « chefs de canton » ou « chefs supérieurs » associés aux Beti/Bulu durant la période coloniale sont en bonne partie des créations ou officialisations de l''administration allemande puis française, distinctes de l''autorité traditionnelle du nkukuma","statut":"atteste"}]'::jsonb,
  null,
  ARRAY['Philippe Laburthe-Tolra, *Les Seigneurs de la forêt : essai sur le passé historique, l''organisation sociale et les normes éthiques des anciens Beti du Cameroun* (Publications de la Sorbonne, 1981)', 'Bôt Ba Njock, « Prééminences sociales et système politico-religieux dans la société traditionnelle Bulu et Fang », *Journal des africanistes*, 1960 — [Persée](https://www.persee.fr/doc/jafr_0037-9166_1960_num_30_2_1922)', '[Le peuple Béti — Alice Pégie Cuisine](https://www.alicepegie.com/le-peuple-beti/)', '[Nature et formes de pouvoir dans les sociétés acéphales — IRD Horizon](https://horizon.documentation.ird.fr/exl-doc/pleins_textes/pleins_textes_5/pt5/travaux_d/01866.pdf)', 'Article académique (Université de Dschang) discutant la nuance du terme « société acéphale » appliqué aux Beti/Bulu — [Revue Akofena](https://www.revue-akofena.com/wp-content/uploads/2022/12/025-Hilaire-ATIOGO_273-284.pdf)']::text[],
  ARRAY['martin-paul-samba', 'charles-atangana']::text[],
  ARRAY['ebolowa', 'rite-initiatique-so']::text[],
  'pret',
  5
);

insert into public.decouverte_items (slug, type, pays, region_ethnie, titre, sous_titre, resume_liste, contenu_fr_texte, contenu_en_texte, statut_fait_legende, image_url, sources, heros_lies, items_lies, statut_contenu, ordre_affichage) values (
  'rite-initiatique-so',
  'coutume',
  'Cameroun',
  'Pays Bulu/Beti, sud/centre Cameroun',
  'Le Sô',
  'Le grand rite d''initiation masculine qui, chez les Beti et les Bulu, transformait l''adolescent en homme accompli',
  'Le Sô était le rite d''initiation majeur des sociétés beti et bulu, réservé aux garçons et étalé sur plusieurs mois : épreuves, réclusion et enseignement transmis par un officiant extérieur au lignage. Il faisait à la fois entrer le jeune homme dans l''âge adulte et purgeait la communauté de fautes qu''elle jugeait devoir expier collectivement. Largement bouleversé par la colonisation et l''évangélisation, il n''est plus pratiqué aujourd''hui sous sa forme ancienne.',
  'Chez les peuples beti, bulu et, plus largement, dans l''ensemble pahouin d''Afrique centrale, le Sô occupait une place centrale parmi les institutions qui organisaient le passage à l''âge adulte. Ce n''était pas seulement un rite de passage individuel : il combinait, selon les travaux de l''anthropologue Philippe Laburthe-Tolra, qui a consacré une partie de son œuvre majeure à la religion beti, deux fonctions étroitement mêlées. D''un côté, une dimension d''expiation collective (le nsem), où une transgression reconnue publiquement par un membre de la communauté déclenchait l''organisation du rite. De l''autre, un authentique parcours initiatique pour un groupe de jeunes garçons, généralement âgés d''une douzaine à une quinzaine d''années, qui en ressortaient reconnus comme des hommes accomplis.

Le processus s''étendait sur plusieurs mois et suivait une série d''étapes rituelles : confession publique de la faute à l''origine du rite, désignation des candidats (chacun encadré par un parrain), plantation d''une corne sacrée près d''un arbre symbolique, puis abattage de cet arbre, série d''épreuves physiques et symboliques vécues en forêt, construction d''un sanctuaire dédié, et enfin une période de réclusion consacrée à l''enseignement des jeunes initiés par les anciens. Un détail organisationnel notable, relevé par plusieurs sources, est que l''officiant principal du rite devait toujours être étranger aux lignages directement concernés, une manière de garantir une forme d''impartialité dans un rituel qui touchait à des affaires de faute et de réparation internes à la communauté. À l''issue du parcours, le jeune homme accédait à des droits et des marques de statut réservés aux initiés, notamment le droit de consommer certains mets jusque-là interdits aux femmes et aux non-initiés, et intégrait le cercle des hommes consultés dans les affaires du village.

Le détail précis des épreuves traversées en forêt reste, par nature, un savoir réservé aux initiés et transmis oralement de génération en génération ; ce n''est pas à une plateforme de vulgarisation d''en détailler le contenu, et le respect de ce secret fait d''ailleurs partie intégrante de ce que le rite cherchait à transmettre. Ce qui est en revanche bien documenté, c''est que le Sô a été profondément bousculé par la rencontre entre les sociétés beti-fang et le christianisme durant la période coloniale : missionnaires et administration coloniale ont, selon les régions et les époques, cherché à l''interdire, le concurrencer ou le remplacer par d''autres formes d''encadrement de la jeunesse. Le rite, dans sa forme ancienne et complète, a ainsi largement disparu au cours du XXe siècle ; il subsiste aujourd''hui surtout comme objet de mémoire, de recherche universitaire et, ponctuellement, de tentatives de revalorisation culturelle, plutôt que comme pratique vivante généralisée.',
  null,
  '[{"affirmation":"Le Sô était un rite d''initiation masculine pratiqué chez les Beti, les Bulu et d''autres groupes pahouins d''Afrique centrale","statut":"atteste"},{"affirmation":"Il combinait une fonction d''expiation collective (nsem) et une fonction de passage à l''âge adulte pour un groupe de garçons","statut":"atteste"},{"affirmation":"Les candidats avaient généralement entre 12 et 15 ans environ","statut":"atteste"},{"affirmation":"L''officiant principal du rite (zomoloa) devait être étranger aux lignages directement concernés par la faute à l''origine du rite","statut":"atteste"},{"affirmation":"Le déroulement détaillé du rite (étapes, symboles, durée exacte) est documenté par l''anthropologie universitaire mais varie selon les sous-groupes et les époques décrites","statut":"debattu"},{"affirmation":"Le contenu précis des épreuves vécues en réclusion relève d''un savoir initiatique protégé, non détaillé publiquement par choix éditorial","statut":"tradition_orale"},{"affirmation":"Le rite, dans sa forme ancienne et complète, a largement disparu au cours de la période coloniale et post-coloniale sous l''effet de l''évangélisation et de l''administration coloniale","statut":"atteste"}]'::jsonb,
  null,
  ARRAY['Philippe Laburthe-Tolra, *Initiations et sociétés secrètes au Cameroun : essai sur la religion beti* (Karthala, 1985), analysé via le compte-rendu de Louis-Vincent Thomas — [Persée, Archives de sciences sociales des religions](https://www.persee.fr/doc/assr_0335-5985_1986_num_62_2_2415_t1_0288_0000_2)', 'Philippe Laburthe-Tolra, *Les Seigneurs de la forêt : essai sur le passé historique, l''organisation sociale et les normes éthiques des anciens Beti du Cameroun* (Publications de la Sorbonne, 1981)', '[La rencontre du christianisme avec le groupe Fang-Beti du Cameroun (analyse de l''évolution du rite Sô dans une société colonisée et évangélisée) — Savoirs UdeSherbrooke](https://savoirs.usherbrooke.ca/handle/11143/12662)', '[Culture Vive – Beti-Fang-Bulu : Le Sô, initiation des garçons — ngun.org](https://www.ngun.org/BetiFang/Initiation.htm)', '[8 rites pratiqués chez les Béti au Cameroun — CamerounWeb](https://www.camerounweb.com/CameroonHomePage/entertainment/8-rites-pratiqu-s-chez-les-B-ti-au-Cameroun-409071)']::text[],
  ARRAY['martin-paul-samba', 'charles-atangana']::text[],
  ARRAY['ebolowa', 'nkukuma-notable-lignage']::text[],
  'pret',
  6
);

insert into public.decouverte_items (slug, type, pays, region_ethnie, titre, sous_titre, resume_liste, contenu_fr_texte, contenu_en_texte, statut_fait_legende, image_url, sources, heros_lies, items_lies, statut_contenu, ordre_affichage) values (
  'bonanjo-palais-des-rois-bell',
  'village',
  'Cameroun',
  'Peuple Sawa, littoral camerounais (Douala)',
  'Bonanjo et le Palais des rois Bell',
  'Le berceau historique des Duala sur la rive du Wouri, où s''est joué le sort de la ville',
  'Sur la rive gauche du fleuve Wouri, le quartier de Bonanjo est l''un des trois villages historiques fondateurs de Douala, avec Akwa et Deido. Il abrite le Palais des rois Bell, résidence royale bâtie en 1905 et surnommée « la Pagode », où a vécu et résisté Rudolf Douala Manga Bell avant son exécution en 1914.',
  'Avant de devenir le centre administratif et économique de Douala, Bonanjo était un village sawa parmi d''autres sur l''estuaire du Wouri, la voie d''eau qui a façonné toute l''histoire du peuple duala. Selon la tradition orale duala, la lignée fondatrice descend d''un ancêtre commun, Mbedi a Mbongo, dont le fils Ewale a Mbedi aurait mené une migration vers l''embouchure du Wouri ; le nom même « Duala » viendrait de « Du''Ewale », « ceux d''Ewale ». Une autre version, transmise par la chefferie Bell elle-même, situe la fondation en 1792, quand le prince Bélè ba Doo prend la tête d''un royaume unifié après la mort de son père Doo la Makongo (le roi Joss), qui aurait régné sur l''ensemble des Duala depuis Bonanjo entre 1756 et 1792. Ces deux récits ne se recoupent pas parfaitement : ils appartiennent à des traditions orales distinctes, propres à des lignages différents, et aucune source académique indépendante ne permet aujourd''hui de trancher entre elles.

Ce qui est mieux établi, c''est la suite : au fil du XIXe siècle, la société duala s''organise en plusieurs chefferies rivales et complémentaires installées sur l''estuaire, dont Bell, Akwa et Deido comptent parmi les plus influentes. Chacune tire sa puissance du commerce fluvial et maritime avec les navires européens, un rôle d''intermédiaire que les Duala occupent de longue date sur cette portion du littoral. C''est cette puissance commerciale qui fait de Bonanjo un enjeu stratégique : en juillet 1884, l''explorateur allemand Gustav Nachtigal y fait signer aux rois Akwa, Bell et Deido les traités qui ouvrent la voie au protectorat allemand du Kamerun.

Le bâtiment le plus emblématique de Bonanjo aujourd''hui est le Palais des rois Bell, construit en 1905 par des bâtisseurs allemands pour le roi Auguste Manga Ndumbe. Sa silhouette, marquée par une succession de toitures étagées, lui vaut le surnom de « la Pagode », donné par l''écrivain français Louis-Ferdinand Céline, qui séjourna au Cameroun en 1916-1917 et évoqua le bâtiment dans « Voyage au bout de la nuit » (1932). C''est dans ce palais qu''a vécu Rudolf Douala Manga Bell, fils d''Auguste Manga Ndumbe, à partir de son accession en 1908 et jusqu''à son arrestation en juillet 1914 par l''administration coloniale allemande, qui le fera exécuter la même année pour son opposition à l''expropriation des terres duala. Le palais reste aujourd''hui classé monument national, même s''il ne sert plus de résidence royale.

En 1910, les autorités allemandes établissent un plan d''urbanisme qui sépare les quartiers indigènes des quartiers européens et exproprient 280 hectares du plateau Joss, provoquant une vive opposition locale, prélude aux tensions qui culmineront avec l''affaire Bell. Bonanjo devient alors le siège des administrations coloniale allemande puis française, un rôle de centre du pouvoir qu''il conserve aujourd''hui comme cœur administratif et des affaires de Douala.',
  null,
  '[{"affirmation":"Bonanjo est l''un des villages historiques fondateurs des Duala sur la rive gauche du Wouri, avec Akwa et Deido","statut":"atteste"},{"affirmation":"La lignée duala descendrait d''un ancêtre commun Mbedi a Mbongo, via son fils Ewale a Mbedi, migré vers l''estuaire du Wouri","statut":"tradition_orale"},{"affirmation":"La chefferie Bell aurait été fondée en 1792 par le prince Bélè ba Doo, après un royaume unifié dirigé par son père Doo la Makongo (roi Joss) depuis Bonanjo (1756-1792)","statut":"tradition_orale"},{"affirmation":"Les deux récits d''origine (migration Ewale a Mbedi / fondation 1792 par Bélè ba Doo) ne se recoupent pas et proviennent de traditions distinctes","statut":"debattu"},{"affirmation":"En juillet 1884, Gustav Nachtigal fait signer aux rois Akwa, Bell et Deido les traités de cession de terres ouvrant la voie au protectorat allemand","statut":"atteste"},{"affirmation":"Le Palais des rois Bell a été construit en 1905 par des bâtisseurs allemands pour le roi Auguste Manga Ndumbe","statut":"atteste"},{"affirmation":"Le surnom « la Pagode » vient de l''écrivain Louis-Ferdinand Céline, qui l''évoque dans « Voyage au bout de la nuit » (1932)","statut":"atteste"},{"affirmation":"Rudolf Douala Manga Bell a vécu au palais de 1908 jusqu''à son arrestation en juillet 1914, avant son exécution la même année","statut":"atteste"},{"affirmation":"En 1910, l''administration allemande a excisé 280 hectares du plateau Joss pour un quartier européen, provoquant une opposition locale","statut":"atteste"},{"affirmation":"Le Palais des rois Bell est aujourd''hui classé monument national et sert de restaurant","statut":"atteste"}]'::jsonb,
  null,
  ARRAY['Wikipédia (FR) — « Palais des rois Bell »', 'Wikipédia (FR) — « Chefferie supérieure du canton Bell »', 'Wikipédia (FR) — « Bonanjo (Douala) »', 'Wikipédia (FR) — « Duala (peuple) »', 'Wikipédia (EN) — « Duala people »', 'Wikipédia (EN) — « Ndumbe Lobe Bell » / « Manga Ndumbe Bell »']::text[],
  ARRAY['rudolf-douala-manga-bell']::text[],
  ARRAY['le-ngondo', 'le-tangue-proue-de-pirogue-sacree']::text[],
  'pret',
  7
);

insert into public.decouverte_items (slug, type, pays, region_ethnie, titre, sous_titre, resume_liste, contenu_fr_texte, contenu_en_texte, statut_fait_legende, image_url, sources, heros_lies, items_lies, statut_contenu, ordre_affichage) values (
  'le-ngondo',
  'coutume',
  'Cameroun',
  'Peuple Sawa, littoral camerounais (Douala)',
  'Le Ngondo, l''assemblée du fleuve',
  'La grande fête sawa qui interroge les esprits du Wouri pour éclairer l''année à venir',
  'Chaque année, de septembre au premier dimanche de décembre, le peuple sawa se réunit à Douala pour le Ngondo : lutte traditionnelle, défilé, concours et artisanat culminent avec un rituel sacré sur le fleuve Wouri, où un initié plonge avec un vase confié aux esprits jengu et en remonte un message pour la communauté. Inscrit au patrimoine culturel immatériel de l''humanité par l''UNESCO en décembre 2024.',
  'Le Ngondo est la grande assemblée traditionnelle du peuple sawa, ce vaste ensemble de communautés côtières du Cameroun dont les Duala forment le cœur. Son nom recouvre à la fois une institution politique et religieuse ancienne et la fête annuelle qui en est aujourd''hui l''expression la plus visible. Le point commun à toutes les versions du récit, qu''elles viennent des historiens ou de la tradition orale sawa elle-même, est le lien indéfectible entre ce peuple et le fleuve Wouri : les Sawa se définissent comme le « peuple de l''eau », et le Ngondo est la manière dont ils entretiennent ce lien, saison après saison, depuis des générations.

Au cœur de la croyance sawa se trouvent les jengu (au pluriel miengu), des esprits de l''eau considérés comme des intermédiaires entre les vivants, les ancêtres et le divin. La tradition veut que les ancêtres duala reposent dans les profondeurs du fleuve et de la mer, et que les miengu veillent sur leurs descendants tout en pouvant leur apporter chance ou avertissement. Le moment le plus sacré du Ngondo est justement la rencontre avec ce monde invisible : sur les rives du Wouri, le premier dimanche de décembre, un prêtre traditionnel ou un initié plonge depuis une pirogue sacrée avec un vase contenant les vœux et préoccupations de la communauté, reste immergé un temps que la tradition orale décrit comme extraordinairement long, puis remonte le récipient. Le message qu''il en tire est réputé guider la vie collective des Sawa jusqu''à l''assemblée suivante. Cette dimension du rituel, transmise par initiation et non par récit public détaillé, reste largement du ressort de la tradition orale : aucune source académique indépendante ne documente précisément son déroulement, ce qui est cohérent avec son caractère volontairement réservé aux initiés.

Autour de ce noyau sacré, le Ngondo s''est étoffé, au fil du XXe siècle, d''un volet festif et populaire bien plus documenté : une caravane parcourt les quartiers traditionnels sawa avec spectacles artistiques, un tournoi de lutte traditionnelle, une foire artisanale et commerciale, un concours de beauté (Miss Ngondo), et l''événement le plus spectaculaire pour le grand public, la course de pirogues géantes sur le Wouri, qui peut réunir des embarcations de plusieurs dizaines de rameurs. L''histoire récente du Ngondo n''est cependant pas linéaire : les sources s''accordent sur le fait que la fête a connu au moins une interruption imposée par les autorités camerounaises avant d''être rétablie, mais elles divergent sur les dates exactes et sur la nature précise de cette interruption. Certaines évoquent une célébration liée au 12 juillet, date anniversaire d''un traité de l''époque coloniale, interrompue après 1972 puis relancée sous une forme déplacée à décembre ; d''autres évoquent une interdiction en 1981 et un rétablissement en 1991. Ces deux récits ne sont pas nécessairement incompatibles (ils pourraient décrire deux moments différents de l''histoire du Ngondo), mais aucune source consultée ne les réconcilie clairement : ce point reste donc débattu.

Ce qui est en revanche solidement établi, c''est la reconnaissance internationale récente de la tradition. En décembre 2024, à Asunción (Paraguay), le Comité intergouvernemental de l''UNESCO pour la sauvegarde du patrimoine culturel immatériel a inscrit le Ngondo, décrit officiellement comme « le culte des oracles de l''eau et les traditions culturelles associées chez les Sawa », sur la Liste représentative du patrimoine culturel immatériel de l''humanité. Cette inscription faisait suite à celle du Nguon, la grande assemblée bamoun, un an plus tôt : deux traditions royales et fluviales camerounaises reconnues coup sur coup par l''institution internationale, un motif de fierté largement relayé par les autorités traditionnelles sawa et le gouvernement camerounais.',
  null,
  '[{"affirmation":"Le Ngondo est la grande assemblée traditionnelle du peuple sawa, centrée sur le culte des esprits de l''eau (jengu/miengu) et pratiquée à Douala sur les rives du Wouri","statut":"atteste"},{"affirmation":"La croyance sawa situe les ancêtres duala dans les profondeurs du fleuve et de la mer, veillés par les esprits jengu","statut":"tradition_orale"},{"affirmation":"Le rituel central consiste en l''immersion d''un vase sacré par un initié, qui en ressort avec un message destiné à guider la communauté","statut":"atteste (pour l''existence du rituel, tel que décrit par l''UNESCO) / tradition_orale (pour son déroulement précis, réservé aux initiés)"},{"affirmation":"La fête comprend un volet festif : caravane, lutte traditionnelle, foire artisanale, concours de beauté et course de pirogues, se déroulant de septembre au premier dimanche de décembre","statut":"atteste"},{"affirmation":"Le Ngondo a connu une interruption imposée par les autorités camerounaises avant d''être rétabli","statut":"atteste (le fait de l''interruption)"},{"affirmation":"Les dates précises de cette interruption (liée au 12 juillet et à 1972, ou interdiction 1981-1991) varient selon les sources et ne sont pas réconciliées","statut":"debattu"},{"affirmation":"Le Ngondo a été inscrit par l''UNESCO sur la Liste représentative du patrimoine culturel immatériel de l''humanité en décembre 2024","statut":"atteste"},{"affirmation":"Cette inscription faisait suite à celle du Nguon (peuple bamoun) en décembre 2023, première inscription camerounaise sur cette liste","statut":"atteste"}]'::jsonb,
  null,
  ARRAY['UNESCO, Patrimoine culturel immatériel — fiche officielle « Ngondo, worship of water oracles and associated cultural traditions among the Sawa » (ich.unesco.org)', 'Wikipédia (EN) — « Ngondo »', 'Wikipédia (FR) — « Ngondo (fête) »', 'Xinhua / english.news.cn — « Cameroon''s Ngondo Festival marks 1st anniversary as UNESCO intangible cultural heritage » (décembre 2025)', 'Assemblée traditionnelle sawa — ngondo.cm', 'Mairie de Douala 1er — « Le Ngondo : une célébration mystique et culturelle des peuples Sawa »']::text[],
  ARRAY['rudolf-douala-manga-bell']::text[],
  ARRAY['bonanjo-palais-des-rois-bell', 'le-tangue-proue-de-pirogue-sacree']::text[],
  'pret',
  8
);

insert into public.decouverte_items (slug, type, pays, region_ethnie, titre, sous_titre, resume_liste, contenu_fr_texte, contenu_en_texte, statut_fait_legende, image_url, sources, heros_lies, items_lies, statut_contenu, ordre_affichage) values (
  'le-tangue-proue-de-pirogue-sacree',
  'objet',
  'Cameroun',
  'Peuple Sawa, littoral camerounais (Douala)',
  'Le Tangué, proue sculptée des pirogues sawa',
  'L''ornement de proue sculpté qui portait le prestige d''un clan sur les grandes pirogues de course du Wouri',
  'Fixé à l''avant des immenses pirogues de course « myolo » du fleuve Wouri, le tangué est une proue de bois sculptée, peinte et chargée de figures animales et symboliques. Bien plus qu''un simple ornement, il portait la protection spirituelle de l''équipage et affichait la puissance du clan duala qui l''avait fait fabriquer, notamment lors des courses coutumières encore associées au Ngondo.',
  'Chez les Sawa, la pirogue n''a jamais été un simple moyen de transport. En langue duala, elle est désignée par le mot « bɔlɔ », que la tradition orale fait dériver de « bɔ » (fin) et « lɔ » (noyade), soit littéralement « la fin des noyades » : un nom qui dit tout de la place de cette embarcation dans la vie d''un peuple qui s''est toujours défini par son rapport au fleuve et à l''océan. Sa fabrication suit un ensemble de règles où le savoir-faire artisanal se mêle étroitement au sacré : le bois est choisi et travaillé selon des rites transmis de génération en génération, et la mise à l''eau d''une nouvelle pirogue s''accompagne, selon la tradition orale sawa, d''offrandes destinées à la confier aux divinités des eaux qui, dans la cosmologie sawa, gouvernent le fleuve.

C''est sur les plus grandes de ces pirogues, les « myolo », embarcations pouvant atteindre 20 à 28 mètres de long et réunir plusieurs dizaines de rameurs, que se fixait le tangué : une pièce de proue amovible, sculptée dans un bois clair et résistant (le bois de bokuka est mentionné pour au moins un exemplaire documenté), présentant des figures hybrides, des animaux stylisés (félins, serpents, oiseaux marins comme le cormoran), parfois une figure mi-humaine mi-simiesque tenant un harpon, l''ensemble rehaussé de couleurs vives où dominait le rouge. Ce tangué n''était pas un simple décor : sa fonction était à la fois magico-religieuse, pour protéger l''équipage et lui assurer la victoire lors des courses coutumières traditionnelles (le « pembisan »), et sociale, pour afficher publiquement la puissance économique et le prestige du clan duala qui l''avait commandé. Les artisans qui les sculptaient restaient, pour la plupart, anonymes : la pièce elle-même, et le clan qu''elle représentait, primaient sur la signature individuelle.

Ces pirogues et leurs proues sculptées ont aussi été les témoins directs de la rencontre, souvent violente, entre le monde sawa et les puissances européennes. Au XIXe siècle, elles portaient le commerce fluvial et maritime qui faisait la richesse des chefferies duala. Sous la colonisation allemande, elles ont aussi été instrumentalisées dans les rituels de pouvoir : le tangué du clan Lock Priso Bell, par exemple, fut emporté par le médecin allemand Max Buchner lors d''une expédition punitive en 1884, et se trouve aujourd''hui au Musée national d''ethnologie de Munich, une pièce que le descendant Alexandre Kum''a Ndumbe III a réclamée en restitution. D''autres tangués ont rejoint, au fil du XXe siècle, des collections privées et muséales occidentales : l''un des exemplaires les mieux documentés, acquis vers 1957 par le chercheur Pierre Harter auprès du prince Ekwala Essaka de Deido, a rejoint la collection Jean-Paul Chazal et a été présenté au Kunsthaus de Zurich en 1970-1971, conservant encore sa coloration rouge d''origine — la marque, disent les spécialistes, de sa participation effective aux courses.

Aujourd''hui, la course de pirogues reste le moment le plus spectaculaire du Ngondo, la grande assemblée sawa célébrée chaque année sur le Wouri. Si les tangués les plus anciens ont largement quitté les rives du fleuve pour les musées et les collections, l''objet reste un symbole fort de l''identité sawa : la preuve qu''un peuple de pêcheurs et de commerçants a su transformer un simple ornement de navigation en véritable œuvre d''art politique et spirituel.',
  null,
  '[{"affirmation":"La pirogue duala est appelée « bɔlɔ », que la tradition orale traduit par « fin des noyades » (bɔ = fin, lɔ = noyade)","statut":"tradition_orale"},{"affirmation":"La fabrication d''une pirogue et sa mise à l''eau s''accompagnent de rites destinés à la confier aux divinités des eaux","statut":"tradition_orale"},{"affirmation":"Les grandes pirogues de course duala, dites « myolo », peuvent mesurer de 20 à 28 mètres de long","statut":"atteste"},{"affirmation":"Le tangué est une proue de bois amovible, sculptée et peinte, fixée à l''avant des pirogues myolo","statut":"atteste"},{"affirmation":"Le tangué avait une fonction à la fois magico-religieuse (protection, victoire à la course) et sociale (affichage du prestige et de la puissance économique du clan)","statut":"atteste"},{"affirmation":"Le nom des artisans sculpteurs de tangués reste généralement inconnu","statut":"atteste"},{"affirmation":"Le tangué du clan Lock Priso Bell a été emporté par le médecin allemand Max Buchner en 1884 et se trouve aujourd''hui au Musée national d''ethnologie de Munich","statut":"atteste"},{"affirmation":"Un descendant de la famille Bell, Alexandre Kum''a Ndumbe III, a demandé la restitution de ce tangué","statut":"atteste"},{"affirmation":"Un tangué documenté (bois de bokuka, 73 x 120 x 44 cm) a été acquis vers 1957 par Pierre Harter auprès du prince Ekwala Essaka de Deido, avant de rejoindre la collection Jean-Paul Chazal","statut":"atteste"},{"affirmation":"La course de pirogues « pembisan »/myolo est l''une des cérémonies coutumières les plus anciennes encore pratiquées à Douala, documentée dès 1960 par Pierre Harter","statut":"atteste"}]'::jsonb,
  null,
  ARRAY['Wikipédia (FR) — « Tangué »', 'Sotheby''s — fiche de vente « Proue de pirogue, Duala, Cameroun » (collection Jean-Paul Chazal, 2024), avec datation, provenance et description iconographique établies par des experts en arts d''Afrique', 'Wikipédia (EN) — « Duala people » (dimensions et usage des pirogues de course)', 'Pierre Harter, « Les courses de pirogues coutumières chez les Duala ou Pembisan a Myoloo Duala », Recherches et Études Camerounaises, 1960 (via le portail Horizon, IRD — document identifié mais non intégralement consulté, contenu en PDF non extractible dans cette session ; citations reprises via les résumés bibliographiques croisés du portail IRD)', 'Le Tamtam du Mboa — « La pirogue dans la tradition sawa : quelle sacralité ? » (source de tradition orale, à traiter avec prudence, sans confirmation académique indépendante trouvée pour l''étymologie exacte et le détail des rites)']::text[],
  ARRAY['rudolf-douala-manga-bell']::text[],
  ARRAY['bonanjo-palais-des-rois-bell', 'le-ngondo']::text[],
  'pret',
  9
);
